AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 4.0
  Exclude:
    - 'vendor/**/*'

Metrics/MethodLength:
  Max: 45

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false
